# Generated by Django 5.0.6 on 2025-11-03 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Например: Тимофей(Юлия)', max_length=255),
        ),
    ]
